title: Yi Su's Running Thoughts
author:
  name: GitHub User
  email: your-email@domain.com
description: >
  This site is for documenting my learnings and thoughts  
show_downloads: false
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: classic
  # Minima date format.
  # The default value is "%b %d, %Y" (e.g. Nov 14, 2023) 
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #date_format: "%b-%d-%Y"    
