title: Yi Su's Running Thoughts
author:
  name: Yi Su
  email: yisu201506@gmail.com

description: >
  This site is for documenting my learnings and thoughts  

show_downloads: false
toc: true

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  math_engine: mathjax

minima:
  skin: classic  
